INSERT INTO [dbo].[Dział] ([Nazwa_Dzialu]) VALUES ('IT')
INSERT INTO [dbo].[Dział] ([Nazwa_Dzialu]) VALUES ('HR')
INSERT INTO [dbo].[Dział] ([Nazwa_Dzialu]) VALUES ('Marketing')
INSERT INTO [dbo].[Pracownik] ([Dzial_ID],[Imie],[Nazwisko],[Data_Zatrudnienia]) VALUES (1,'Jan','Kowlaski','20101210')
INSERT INTO [dbo].[Pracownik] ([Dzial_ID],[Imie],[Nazwisko],[Data_Zatrudnienia]) VALUES (2,'Adam','Mazur','20101210')
INSERT INTO [dbo].[Pracownik] ([Dzial_ID],[Imie],[Nazwisko],[Data_Zatrudnienia]) VALUES (3,'Kamil','Poplawski','20101210')
INSERT INTO [dbo].[Pracownik] ([Dzial_ID],[Imie],[Nazwisko],[Data_Zatrudnienia]) VALUES (3,'Marek','Walczak','20101210')
INSERT INTO [dbo].[Pracownik] ([Dzial_ID],[Imie],[Nazwisko],[Data_Zatrudnienia]) VALUES (3,'Cezary','Kosior','20101210')
INSERT INTO [dbo].[Ocena] ([Wartosc] ,[Opis]) VALUES (1 ,'Dramat')
INSERT INTO [dbo].[Ocena] ([Wartosc] ,[Opis]) VALUES (2 ,'Bylo zle')
INSERT INTO [dbo].[Ocena] ([Wartosc] ,[Opis]) VALUES (3 ,'Srednio')
INSERT INTO [dbo].[Ocena] ([Wartosc] ,[Opis]) VALUES (4 ,'OK')
INSERT INTO [dbo].[Ocena] ([Wartosc] ,[Opis]) VALUES (5 ,'Super, to jest to!')